#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - staging
    - v1.0
    - v2.0

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# environment variables
environment:
  AZURE_STORAGE_ACCESS_KEY_STAGING:
    secure: LPX3Gv4dUzZ187kD3CZMsRWR1qNB9UM287fR1vh6FD4zAtUTzbPc5Hrh4syNokgYVPEN7JHxN0NL8Vt13DeCvW4STUyyFK+VgdDt5nTseMRsNbVST6ZYqmN19mF15yzi
  AZURE_STORAGE_ACCESS_KEY:
    secure: pLJQvFOvO9DWeIX7KGdhUOSyEL7IH8CPegPlFMeZNod2fCeQIZ679KR8deYzrGeWKOAPi8j1+P0m4RSuorWnvXrU2MrJaxer912WbQHZ4Z/D8Q4kGFFwU3siJS9OzOap

# scripts that are called at very beginning, before repo cloning
init:
  - npm install gulp -g
  - git config --global core.autocrlf input

# build cache to preserve files/folders between builds
cache:
  - node_modules                    # local npm modules

# scripts that run after cloning repository
install:
  - npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: $splitted = $env:APPVEYOR_BUILD_VERSION.Split(".")
  - ps: $version = $splitted[0] + "." + $splitted[1]
  - ps: gulp deploy --version $version

after_build:
  - cd dist\themes
  - 7z a %APPVEYOR_BUILD_FOLDER%\themes.zip "**\*.*" -r -x!".gitkeep" -x!".gitignore" -x!"*.map"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file
  - path: themes.zip
    name: themes
    type: zip

deploy:
  # Staging
  - provider: AzureBlob
    storage_account_name: snipcartcdndev
    storage_access_key:
      secure: LPX3Gv4dUzZ187kD3CZMsRWR1qNB9UM287fR1vh6FD4zAtUTzbPc5Hrh4syNokgYVPEN7JHxN0NL8Vt13DeCvW4STUyyFK+VgdDt5nTseMRsNbVST6ZYqmN19mF15yzi
    container: themes
    artifact: themes
    unzip: true
    on:
      branch: staging

  # Production
  - provider: AzureBlob
    storage_account_name: snipcartpublic
    storage_access_key:
      secure: pLJQvFOvO9DWeIX7KGdhUOSyEL7IH8CPegPlFMeZNod2fCeQIZ679KR8deYzrGeWKOAPi8j1+P0m4RSuorWnvXrU2MrJaxer912WbQHZ4Z/D8Q4kGFFwU3siJS9OzOap
    container: themes
    artifact: themes
    unzip: true
    on:
      branch:
        - master
        - v1.0
        - v2.0

after_deploy:
  - cd %APPVEYOR_BUILD_FOLDER%\tools\AzureStorageContentTypeUpdater
  # Staging
  - if /i "%APPVEYOR_REPO_BRANCH%"=="staging" AzureStorageContentTypeUpdater.exe -a snipcartcdndev -k %AZURE_STORAGE_ACCESS_KEY_STAGING% -c themes --lowercase true
  # Production
  - if /i "%APPVEYOR_REPO_BRANCH%"=="master" AzureStorageContentTypeUpdater.exe -a snipcartpublic -k %AZURE_STORAGE_ACCESS_KEY% -c themes --lowercase true
  - if /i "%APPVEYOR_REPO_BRANCH%"=="v1.0" AzureStorageContentTypeUpdater.exe -a snipcartpublic -k %AZURE_STORAGE_ACCESS_KEY% -c themes --lowercase true
  - if /i "%APPVEYOR_REPO_BRANCH%"=="v2.0" AzureStorageContentTypeUpdater.exe -a snipcartpublic -k %AZURE_STORAGE_ACCESS_KEY% -c themes --lowercase true
